import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * The app's version, stated in two files, checked to agree.
 *
 * `app/app.json` is the manifest — the number the manual's cover is generated
 * from and the one every doc points at. `app/android/app/build.gradle` is what
 * actually ends up in the APK, because `android/` is committed rather than
 * generated by prebuild, so nothing propagates one to the other.
 *
 * `CLAUDE.md` tells you to verify a build by comparing the installed
 * `versionName` against `app/app.json` — which is not the file that produced it.
 * A release that bumped the manifest and not the gradle file would ship an APK
 * whose version reads as the previous one, pass that check by inspecting the
 * wrong file, and be indistinguishable on a device from the release before it.
 * `docs/DEPLOY.md` asks a person to keep the two in step; this is what makes
 * forgetting fail loudly.
 *
 * `versionCode` is deliberately not checked against anything: it is Android's
 * own monotonic counter and has no counterpart in the manifest.
 *
 * Lives in `functions/test/unit` because that workspace is the only one here
 * with a runner wired up — same reasoning as `emulatorPorts.test.ts` next door.
 */
const REPO = resolve(import.meta.dirname, '../../..');
const read = (p: string) => readFileSync(resolve(REPO, p), 'utf8');

describe('the shipped version', () => {
  const manifest = JSON.parse(read('app/app.json')).expo.version as string;
  const gradle = read('app/android/app/build.gradle').match(/versionName\s+"([^"]+)"/)?.[1];

  it('is a version at all in both files', () => {
    expect(manifest).toMatch(/^\d+\.\d+\.\d+$/);
    expect(gradle).toMatch(/^\d+\.\d+\.\d+$/);
  });

  it('is the same in the manifest and in the APK', () => {
    expect(gradle).toBe(manifest);
  });
});
